name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - master
      - develop

jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Pull base image
        run: docker pull ghcr.io/pytrackdat/pytrackdat:latest
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: pytrackdat/pytrackdat
          push: ${{ github.event_name != 'pull_request' }}
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
